### ISSUE TITLE
Allow importing of just .svg?

### ISSUE THREAD

**Issue by spacedawwwg** [SnowdogApps/snowpack-vue-svg-plugin#1]
I'm just wondering why the plugin is hard coded to only import `.vue.svg`?

Maybe this could be a config option?

**Comment by Igloczek** [comment]
The main reason why I picked the `.vue.svg` is Astro, that is already handling `.svg` imports in other way, so I prefer to avoid any collisions.

Although I think the config option for this setting is a good idea.

**Comment by spacedawwwg** [comment]
> The main reason why I picked the `.vue.svg` is Astro, that is already handling `.svg` imports in other way, so I prefer to avoid any collisions.
> 
> Although I think the config option for this setting is a good idea.

Got you! I think that'd be nice - My use case is that I'm mainly using Vue components (most without hydration) over Astro components, so wouldn't really want to rename all my svg's. So In my scenario (and I imagine others) being able to configure it would be rather useful.

**Comment by Igloczek** [comment]
Released as 2.0.0. 

Thanks for help Paul 🙇
